### ISSUE TITLE
add some genres

### ISSUE THREAD

**Issue by GigaGiorgadze** [ninadarbaidze/movie-quotes-front-ninadarbaidze#35]
![image](https://user-images.githubusercontent.com/75663118/189316927-7d156c92-3cb4-4154-bc8b-3ff3e2e6be5d.png)

**Comment by ninadarbaidze** [comment]
I added genres from swagger, not changed any code not in front nor in back, how can we close this issue?

**Comment by GigaGiorgadze** [comment]
like this :)
