### ISSUE TITLE
i use this second email as google account i should not be able to use it as second email

### ISSUE THREAD

**Issue by GigaGiorgadze** [ninadarbaidze/movie-quotes-front-ninadarbaidze#54]
![image](https://user-images.githubusercontent.com/75663118/189597767-0099d206-ef3a-49a5-ad1f-a6cec658b065.png)

**Comment by ninadarbaidze** [comment]
fixed on the backend, can you try again?

**Comment by GigaGiorgadze** [comment]
i will check everything when u finish everything

**Comment by GigaGiorgadze** [comment]
nope  i can still add:
![image](https://user-images.githubusercontent.com/75663118/189835218-4d1bf7ea-b8d2-458d-8bfb-47f55fde82b3.png)

**Comment by GigaGiorgadze** [comment]
maybe i need to create new account? like for u to record this gmail user? if this is case please clear your database i really do not have left anymore emails xD

**Comment by ninadarbaidze** [comment]
Giga I check for duplicate values after user clicks save, before that I only update DOM. Error doesn't popup after clicking save button?

**Comment by GigaGiorgadze** [comment]
ah i see, give me sec

**Comment by GigaGiorgadze** [comment]
yep works
