### ISSUE TITLE
mail does not come when im adding new mail on user profile, idk maybe its just late and thing with google but still check, i will tell u if it comes later

### ISSUE THREAD

**Issue by GigaGiorgadze** [ninadarbaidze/movie-quotes-front-ninadarbaidze#55]

**Comment by ninadarbaidze** [comment]
Giga I checked on both local and production and email was sent, maybe it's in spam folder?

**Comment by GigaGiorgadze** [comment]
nope not really its still not sending, email is gigagiorgadze@redberry.ge check mongodb maybe that user is already created and some conflict happened

**Comment by ninadarbaidze** [comment]
yep, there's a conflict because this email is also used in the google account. I fixed the other issue to check google mails also, I had that logic and don't know whats the problem yet. so I comment on this when I fix the other issue

**Comment by GigaGiorgadze** [comment]
well then this is same as the other one close this one alonegisde that issue with same emails
