### ISSUE TITLE
few problems with changing password workflow

### ISSUE THREAD

**Issue by GigaGiorgadze** [ninadarbaidze/movie-quotes-front-ninadarbaidze#67]
i changed password and got redirected to newsfeed, firstly do not do that, just take me out of edit mode and leave me on same page,
also when i came back to profile it was still in edit mode and this notification stayed there:
![image](https://user-images.githubusercontent.com/75663118/189834943-e247150a-7c11-4b20-82bd-e3dc2e9089a1.png)
edit mode and all notifications should clear when i change page

**Comment by GigaGiorgadze** [comment]
hide two inputs for new passwords after i save
![image](https://user-images.githubusercontent.com/75663118/189871036-3cd3943a-6340-4f06-a23d-fed25d4d27a7.png)

**Comment by ninadarbaidze** [comment]
I cleared password inputs on submit, security wise was more correct

**Comment by GigaGiorgadze** [comment]
no no no, just remove those two bottom inputs, just like when i go to profile page for first time

**Comment by GigaGiorgadze** [comment]
![error](https://user-images.githubusercontent.com/75663118/190102605-7b3a0a82-03cf-4c72-8d4c-fc3a26485d93.gif)
i didn't even edit email
