### ISSUE TITLE
500 error in front 

### ISSUE THREAD

**Issue by GigaGiorgadze** [ninadarbaidze/movie-quotes-front-ninadarbaidze#69]
![image](https://user-images.githubusercontent.com/75663118/189837247-5ac22292-be5c-4f85-9e17-1514aef807a4.png)
steps:

- add quote from movie show page
- go to newsfeed
- press new quote button 
this error does not happen if i reload page

**Comment by ninadarbaidze** [comment]
can I delete all your accounts from database? When I change things in backend old accounts doesn't work because logic is changed

**Comment by GigaGiorgadze** [comment]
sure i do not have emails left anymore anyway :cry:

**Comment by GigaGiorgadze** [comment]
![500](https://user-images.githubusercontent.com/75663118/189872433-69975e05-f0a2-476d-be9e-171aba3180ac.gif)

same
